stages:
  - validate
  - plan
  - deploy
  - destroy

validate:terraform:
  image: 
    name: hashicorp/terraform:1.1.8
    entrypoint: [""]
  tags: 
    - docker
  stage: validate
  when: always
  script:
    - terraform init
    - terraform validate

plan:terraform:
  image: 
    name: hashicorp/terraform:1.1.8
    entrypoint: [""]
  tags:
    - docker
  stage: plan
  when: manual
  only: 
    - tags
  script:
    - terraform init
    - terraform plan

deploy:terraform:
  image: 
    name: hashicorp/terraform:1.1.8
    entrypoint: [""]
  tags:
    - docker
  stage: deploy
  when: manual
  only: 
    - tags
  script:
    - terraform init
    - terraform plan
    - terraform apply -auto-approve

destroy:terraform:
  image: 
    name: hashicorp/terraform:1.1.8
    entrypoint: [""]
  tags:
    - docker
  stage: destroy
  when: manual
  only: 
    - tags
  script:
    - terraform -chdir=course-setup/infrastructure/ init
    - terraform workspace select ${CLASS_NAME} || terraform workspace new ${CLASS_NAME}
    - terraform -chdir=course-setup/infrastructure/ plan -var="cluster_count=${CLUSTERS}" -var="class_name=${CLASS_NAME}" -destroy -out ${CLASS_NAME}.plan
    - terraform -chdir=course-setup/infrastructure/ destroy
  dependencies:
    - deploy:terraform

  
